# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='test',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
