# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_message_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='test',
        ),
    ]
