# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
